# Generated by Django 3.2.8 on 2021-10-05 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211005_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='create_at',
            new_name='post_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
